### ISSUE TITLE
RuleBook Startup error

### ISSUE THREAD

**Issue by XipsAhoy** [Jikoo/RuleBooks#1]
Hi, can you help me, I am using the latest version and when I load the plugin, this shows up:

`[12:14:05 ERROR]: Could not load 'plugins\RuleBooks.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: Unsupported API version 1.16
        at org.bukkit.craftbukkit.v1_15_R1.util.CraftMagicNumbers.checkSupported(CraftMagicNumbers.java:276) ~[Paper-1.15.2-b387(2).jar:git-Paper-387]
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:133) ~[Paper-1.15.2-b387(2).jar:git-Paper-387]
        at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:397) ~[Paper-1.15.2-b387(2).jar:git-Paper-387]
        at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:305) ~[Paper-1.15.2-b387(2).jar:git-Paper-387]
        at org.bukkit.craftbukkit.v1_15_R1.CraftServer.loadPlugins(CraftServer.java:360) ~[Paper-1.15.2-b387(2).jar:git-Paper-387]
        at net.minecraft.server.v1_15_R1.DedicatedServer.init(DedicatedServer.java:234) ~[Paper-1.15.2-b387(2).jar:git-Paper-387]
        at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:909) ~[Paper-1.15.2-b387(2).jar:git-Paper-387]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_261]
[12:14:05 WARN]: Initializing Legacy Material Support. Unless you have legacy plugins and/or data this is a bug!
[12:14:11 WARN]: Legacy plugin CommandBook v2.4:1692-75bb1c8,master does not specify an api-version.
[12:14:11 ERROR]: Could not load 'plugins\CommandBook.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: java.lang.NoClassDefFoundError: com/sk89q/minecraft/util/commands/CommandPermissionsException
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:141) ~[Paper-1.15.2-b387(2).jar:git-Paper-387]
        at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:397) ~[Paper-1.15.2-b387(2).jar:git-Paper-387]
        at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:305) ~[Paper-1.15.2-b387(2).jar:git-Paper-387]
        at org.bukkit.craftbukkit.v1_15_R1.CraftServer.loadPlugins(CraftServer.java:360) ~[Paper-1.15.2-b387(2).jar:git-Paper-387]
        at net.minecraft.server.v1_15_R1.DedicatedServer.init(DedicatedServer.java:234) ~[Paper-1.15.2-b387(2).jar:git-Paper-387]
        at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:909) ~[Paper-1.15.2-b387(2).jar:git-Paper-387]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_261]
Caused by: java.lang.NoClassDefFoundError: com/sk89q/minecraft/util/commands/CommandPermissionsException
        at java.lang.Class.forName0(Native Method) ~[?:1.8.0_261]
        at java.lang.Class.forName(Unknown Source) ~[?:1.8.0_261]
        at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:68) ~[Paper-1.15.2-b387(2).jar:git-Paper-387]
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:137) ~[Paper-1.15.2-b387(2).jar:git-Paper-387]
        ... 6 more
Caused by: java.lang.ClassNotFoundException: com.sk89q.minecraft.util.commands.CommandPermissionsException
        at java.net.URLClassLoader.findClass(Unknown Source) ~[?:1.8.0_261]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:171) ~[Paper-1.15.2-b387(2).jar:git-Paper-387]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:100) ~[Paper-1.15.2-b387(2).jar:git-Paper-387]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_261]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_261]
        at java.lang.Class.forName0(Native Method) ~[?:1.8.0_261]
        at java.lang.Class.forName(Unknown Source) ~[?:1.8.0_261]
        at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:68) ~[Paper-1.15.2-b387(2).jar:git-Paper-387]
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:137) ~[Paper-1.15.2-b387(2).jar:git-Paper-387]
        ... 6 more`

Also, I am using spigot 1.15.2

Thank you.

**Comment by Jikoo** [comment]
1.0.1's release clearly states that it's for 1.16. Pretty sure you can safely change the api-version packed yourself, but I'll look into lower versions.

**Comment by XipsAhoy** [comment]
How can I change the api version?

**Comment by Jikoo** [comment]
You would have to extract the plugin.yml from the archive, edit it, and replace it.

**Comment by Jikoo** [comment]
Release can be found [here](https://github.com/Jikoo/RuleBooks/releases/latest).
